# Site settings
title: Real Time Weather
description: > # 
  Real time weather using eeGeo 3D maps
baseurl: ""

# Build settings
exclude: [src/realtime-weather-app, Gemfile, Gemfile.lock, package.json, README.md, webpack.config*, node_modules/]
markdown: kramdown
