export const UPDATE_LOCAL_TIME = "UPDATE_LOCAL_TIME";
export const UPDATE_TIME_OF_DAY = "UPDATE_TIME_OF_DAY";
export const SET_ACTIVE_TIMELINE_INDEX = "SET_ACTIVE_TIMELINE_INDEX";
export const UPDATE_TIMELINE_BASE_TIME = "UPDATE_TIMELINE_BASE_TIME";
export const UPDATE_DST_OFFSET = "UPDATE_DST_OFFSET";